# Generated by Django 2.1.11 on 2019-08-10 01:45

from django.db import migrations, models
import django.db.models.deletion
import dynamic_forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('form', dynamic_forms.models.FormField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', dynamic_forms.models.ResponseField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Survey')),
            ],
        ),
    ]
